### ISSUE TITLE
Website incompatible with higher node versions

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#784]
**Describe the bug**
The web application only works in 10.* versions of node. Incompatible with higher node versions. 

**To Reproduce**
1. Run the application locally, with higher / lower node versions installed.
2. check out the console errors.

**Expected behaviour**
The applications should be compatible with higher node versions.

**Screenshots**
![Screenshot from 2020-04-14 13-26-56](https://user-images.githubusercontent.com/43489708/79200436-0eddf000-7e54-11ea-9b3f-59bd1792aa56.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by divyanshu-rawat** [comment]
1 - `rm -rf node_ modules`
2 - `Remove package-lock.json`
3 - `switch node version`.
4 -` npm install`
5 - `npm start`

I think this should fix the problem, your node sass bindings are for different version, so you switched the version after npm install I suppose, let me know.

**Comment by Dishebh** [comment]
> 1 - `rm -rf node_ modules`
> 2 - `Remove package-lock.json`
> 3 - `switch node version`.
> 4 -` npm install`
> 5 - `npm start`
> 
> I think this should fix the problem, your node sass bindings are for different version, so you switched the version after `npm install` I suppose, let me know.

The issue still remains. I removed the `node_modules` and `package-lock.json`, switched to the latest version of node and did `npm install`.

**Comment by divyanshu-rawat** [comment]
@Dishebh please have a look in this PR, https://github.com/Ignitus/Ignitus-client/pull/793 in develop we are running node.js v11. 
Implying app is compatible with higher node version, so I am closing the issue for now.
